# Generated by Django 4.2.4 on 2023-08-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentnew',
            fields=[
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('registrationNumber', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.IntegerField(null=True)),
                ('gender', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gpa12', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('gpaBtech', models.DecimalField(decimal_places=2, max_digits=5)),
                ('backlogs', models.CharField(max_length=50)),
                ('degree', models.CharField(default='YourDefaultValueHere', max_length=100)),
                ('project_url', models.URLField()),
                ('skills', models.CharField(default='', max_length=100)),
                ('languages', models.IntegerField(null=True)),
            ],
        ),
    ]
