# Generated by Django 4.2.4 on 2023-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expertisearea_adminregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregistration',
            name='feedback',
            field=models.CharField(default='', max_length=150),
        ),
    ]
