# Generated by Django 4.2.4 on 2023-08-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adminregistration_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregistration',
            name='area_of_expertise',
        ),
        migrations.DeleteModel(
            name='ExpertiseArea',
        ),
    ]
