# Generated by Django 4.2.4 on 2023-08-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentlogin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studentlogin',
        ),
    ]
