# Generated by Django 4.2.4 on 2023-08-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_studentlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminlogin',
        ),
    ]
