# Generated by Django 4.2.4 on 2023-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_adminlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnew',
            name='resume',
            field=models.FileField(default='', upload_to='student_resumes/'),
        ),
    ]
