# Generated by Django 4.2.4 on 2023-10-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_studentnew_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('salary_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills_required', models.TextField()),
            ],
        ),
    ]
