# Generated by Django 4.2.4 on 2023-10-04 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_studentquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquery',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
