# Generated by Django 4.2.4 on 2023-10-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_studentquery_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='skills_required',
            field=models.CharField(default='', max_length=100),
        ),
    ]
