# Generated by Django 4.2.4 on 2023-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_company_skills_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnew',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
