# Generated by Django 4.2.4 on 2023-10-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_studentnew_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnew',
            name='password',
        ),
    ]
