# Generated by Django 4.2.4 on 2023-10-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_studentnew_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default='', upload_to='student_resumes/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentnew')),
            ],
        ),
    ]
