# Generated by Django 4.2.4 on 2023-10-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_appliedstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedstudents',
            name='id',
        ),
        migrations.AlterField(
            model_name='appliedstudents',
            name='student',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
