# Generated by Django 4.2.4 on 2023-10-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_appliedstudents_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedstudents',
            name='name',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appliedstudents',
            name='student',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='appliedstudents',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.studentnew'),
        ),
    ]
