# Generated by Django 4.2.4 on 2023-10-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_appliedstudents_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnew',
            name='dob',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
