# Generated by Django 4.2.4 on 2023-10-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_studentnew_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquery',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
