# Generated by Django 4.2.4 on 2023-10-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_studentquery_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentQuery',
            new_name='StudentQueries',
        ),
    ]
